version: '2'
services:
  store:
    image: xingfuryda/osm-store
    environment:
      POSTGRES_PASSWORD: password1  
  style:
    image: xingfuryda/osm-style    
    volumes:
     - "/c/Users/projects:/home/root/projects"
    ports:
     - "3000:3000"
    environment:
      BOUNDS: -156.36,18.69,-154.49,20.5    # eg: -166.51,14.58,-148.94,27.07
      MINZOOM: 7
      MAXZOOM: 14
      FILENAME: Hawaii
    command: exportsource  
